import Head from "next/head";
import Hero from "../components/Hero";


export default function Home() {
  return (
    <>
    <Head>
      <title>XI RPL 3</title>
      <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/xirpl3.png" />
    </Head>
    <div>
      <Hero
        heading="RPL 3 SLEBEW"
        message="Sebaiknya Jangan Terlalu Gegabah"/>

    </div>
    </>
  )
}
